fix \n escape

diff --git a/golf b/golf
--- a/golf
+++ b/golf
@@ -26,7 +26,7 @@ fi
 OPTS=$(getopt -o vhns: --long expedite,help: -n 'parse-options' -- "$@")
 
 if [ $? != 0 ]; then
-	echo "failed to parse options" >&2
+	printf "failed to parse options" >&2
 	exit 1
 fi
 
@@ -81,7 +81,7 @@ build_readme() {
 	URL="https://gist.githubusercontent.com/gretzky/19f241a2db9f119853019a40be8d0242/raw/702ce9ec40a51cbf3563047f6ea593a2ff637c4b/readme.md"
 	curl "$URL" -o $proj/README.md >/dev/null 2>&1
 	sleep 1
-	echo "# $proj\n" | cat - $proj/README.md | sponge $proj/README.md
+	printf "# $proj\n" | cat - $proj/README.md | sponge $proj/README.md
 }
 
 build_gitignore() {
@@ -143,7 +143,7 @@ build_editorconfig() {
 			style=$style | rev | cut -c 2- | rev
 		fi
 
-		echo "\n[*.$lang]\nindent_style = ${style}\nindent_size = ${size}" >>$proj/.editorconfig
+		printf "\n[*.$lang]\nindent_style = ${style}\nindent_size = ${size}" >>$proj/.editorconfig
 	}
 	exec 3>&-
 }
@@ -170,10 +170,10 @@ get_license() {
 	fi
 	curl -s "https://api.github.com/licenses/$1" | jq -r '.body' >>$proj/LICENSE
 
-	echo "## License\n" >>$proj/README.md
-	echo "[${1^^}](./LICENSE).\n" >>$proj/README.md
-	echo "## Shoutouts\n" >>$proj/README.md
-	echo "* props to ppl or code\n" >>$proj/README.md
+	printf "## License\n" >>$proj/README.md
+	printf "[${1^^}](./LICENSE).\n" >>$proj/README.md
+	printf "## Shoutouts\n" >>$proj/README.md
+	printf "* props to ppl or code\n" >>$proj/README.md
 }
 
 generate_license() {
